name: Convert Markdown to PDF
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Combine Markdown files
        run: |
          mkdir -p combined
          cat docs/*.md > combined/combined.md

      - name: Convert combined Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: combined
          output_dir: pdfs
          build_html: false

      - uses: actions/upload-artifact@v4
        with:
          name: pdf-document
          path: pdfs